---
- name: Provision LAMP web server
  hosts: all
  roles:
    - { role: Aplyca.LAMP, tags: ["lamp"] }
  post_tasks:
    - name: Test if Apache is installed and running
      uri:
        url: "http://localhost"
        status_code: 403
      changed_when: False
    - name: Test if MySQL extension for PHP is installed
      shell: "php -i"
      register: result_php
      failed_when: "'mysql' not in result_php.stdout"
      changed_when: False
    - name: Test if PHP module for Apache is installed
      shell: "apachectl -M"
      register: result_apache
      failed_when: "'php' not in result_php.stdout"
      changed_when: False
    - name: Test if MySQL is running
      become: yes
      shell: "mysqladmin status"
      changed_when: False
