---
- name: Make sure the custom enabled configuration are present
  sudo: yes
  file:
    src: "../{{ apache['conf_available_path'] }}/custom.conf"
    path: "{{ apache['server_root'] }}/{{ apache['conf_enabled_path'] }}/z20-custom.conf"
    state: link
    force: yes
  notify: reload apache    
  