---
- name: Add custom configuration for Apache
  become: yes
  template:
    src: "custom.conf.j2"
    dest: "{{ apache.server_root }}/{{ apache.conf_available_path }}/custom.conf"
  notify: reload apache
