Vagrant.configure(2) do |config|
  config.vm.define "ansible-role-php.vagrant", primary: true, autostart: true do |config_machine|
      #Assigning a provider
      config_machine.vm.provider :virtualbox do |virtualbox, override|
          virtualbox.name = "Testing Ansible PHP role"
		  #override.vm.box = "chef/centos-7.0"
		  override.vm.box = "ubuntu/trusty64"
          
		  # Configuring network
          #override.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
      end
	  
      # Asinging a provisioner
      config_machine.vm.provision :ansible, run: "always" do |provisioner|
          provisioner.playbook = "vagrant.yml"
      end
  end
end